# LOREN HARTMAN

l_line_1 = "L     "
l_line_2 = "LLLLL "

o_line_1 = " OOO  "
o_line_2 = "O   O "

r_line_1 = "RRRR  "
r_line_2 = "R   R "
r_line_3 = "R R   "
r_line_4 = "R  R  "
r_line_5 = "R   R "

e_line_1 = "EEEEE "
e_line_2 = "E     "
e_line_3 = "EEE   "

n_line_1 = "N   N "
n_line_2 = "NN  N "
n_line_3 = "N N N "
n_line_4 = "N  NN "


line_1 = l_line_1 + o_line_1 + r_line_1 + e_line_1 + n_line_1
line_2 = l_line_1 + o_line_2 + r_line_2 + e_line_2 + n_line_2
line_3 = l_line_1 + o_line_2 + r_line_2 + e_line_2 + n_line_3
line_4 = l_line_1 + o_line_2 + r_line_1 + e_line_3 + n_line_4
line_5 = l_line_1 + o_line_2 + r_line_3 + e_line_2 + n_line_1
line_6 = l_line_1 + o_line_2 + r_line_4 + e_line_2 + n_line_1
line_7 = l_line_2 + o_line_1 + r_line_5 + e_line_1 + n_line_1

print(line_1)
print(line_2)
print(line_3)
print(line_4)
print(line_5)
print(line_6)
print(line_7)
